### Gerar comprovativo em PDF
GET http://localhost:5000/venda/5/comprovativo/pdf/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsInN0YXR1cyI6IkFUSVZPIiwiaWF0IjoxNzkwNjgwMzg5LCJleHAiOjE3OTA3MDkxODl9.SN1rJSpVYazhluZeacLuEnZ7NZyjnUbWz2id2cMjDe8