### Gerar comprovativo em PDF
POST http://localhost:5000/faturacao/saft/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsInN0YXR1cyI6IkFUSVZPIiwiaWF0IjoxNzkwNzk5NTc5LCJleHAiOjE3OTA4MjgzNzl9.SS4otlpvL2GT_8yz9Tkg0RjUVvMUHhOvem3-6KWNsG8

{
    "dataInicio": "2026-09-01",
    "dataFim": "2026-09-30"
}