-- AlterTable
ALTER TABLE `logs_auditoria` MODIFY `acao` ENUM('CREATE', 'LOGIN', 'UPDATE', 'DELETE', 'CANCELAR_VENDA', 'AJUSTE_STOCK', 'ALTERAR_PRECO', 'ALTERAR_ROLE', 'GERAR_NOTA_CREDITO') NOT NULL DEFAULT 'UPDATE';
